plugins {
    id 'java'
}

allprojects {
    group = 'com.onionmcc'
    version = '1.0.0-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'

    if (project.name != 'launcher') {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
        tasks.withType(JavaCompile).configureEach {
            options.release = 8
        }
    } else {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    dependencies {
        implementation 'com.google.code.gson:gson:2.10.1'
        implementation 'org.slf4j:slf4j-api:2.0.9'
        implementation 'org.slf4j:slf4j-simple:2.0.9'
        implementation 'net.java.dev.jna:jna:5.14.0'
        implementation 'net.java.dev.jna:jna-platform:5.14.0'
    }

    jar {
        manifest {
            attributes(
                'Implementation-Title': project.name,
                'Implementation-Version': project.version
            )
        }
    }
}
